# Generated by Django 3.2.11 on 2022-11-05 17:21
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bikerrr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='bike',
            name='id',
        ),
        migrations.RemoveField(
            model_name='bike',
            name='purchaseDate',
        ),
        migrations.RemoveField(
            model_name='bikecategory',
            name='stock',
        ),
        migrations.AddField(
            model_name='bikecategory',
            name='stockCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bike',
            name='modelNumber',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseDate', models.DateTimeField(null=True)),
                ('bikeInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikerrr.bike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BikeCategoryColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAvailable', models.BooleanField(default=False)),
                ('bikeCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikerrr.bikecategory')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikerrr.colors')),
            ],
        ),
    ]
