# Generated by Django 3.2.11 on 2022-11-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikerrr', '0002_auto_20221105_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='warranty',
            field=models.IntegerField(default=0),
        ),
    ]
